import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { fonts } from '../../theme/typography';

export const styles = StyleSheet.create({
  root: { flex: 1, paddingVertical: 2 },
  field: { flex: 1, minHeight: 410, borderRadius: 23, overflow: 'hidden', borderWidth: 2, borderColor: colors.white, position: 'relative' },
  fieldContent: { flex: 1, position: 'relative' },
  mapImage: { borderRadius: 21 },
  compactHud: { position: 'absolute', top: 5, left: 6, right: 6, zIndex: 2000, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  stageHud: { fontFamily: fonts.extraBold, fontSize: 9, color: colors.white, backgroundColor: 'rgba(42,83,153,0.82)', borderRadius: 9, paddingHorizontal: 7, paddingVertical: 4 },
  enemyHud: { fontFamily: fonts.extraBold, fontSize: 9, color: colors.white, backgroundColor: 'rgba(167,37,48,0.84)', borderRadius: 9, paddingHorizontal: 7, paddingVertical: 4 },
  core: { position: 'absolute', left: '50%', bottom: 0, alignItems: 'center', zIndex: 1000, borderRadius: 24 },
  coreReady: { backgroundColor: 'rgba(255,220,91,0.22)', borderWidth: 2, borderColor: colors.yellow },
  corePressed: { transform: [{ scale: 0.92 }] },
  allyName: { fontFamily: fonts.extraBold, fontSize: 8, color: colors.blue, backgroundColor: 'rgba(255,255,255,0.9)', paddingHorizontal: 4, borderRadius: 5 },
  castleHitFlash: { ...StyleSheet.absoluteFill, zIndex: 900 },
  bossSpecialAttackFlash: { ...StyleSheet.absoluteFill, zIndex: 850 },
  bossHealthHud: { position: 'absolute', alignSelf: 'center', zIndex: 2300 },
  bossHealthLabelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 3 },
  bossHealthName: { fontFamily: fonts.extraBold, fontSize: 10, color: colors.red, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 5, paddingHorizontal: 5 },
  bossHealthValue: { fontFamily: fonts.extraBold, fontSize: 9, color: colors.white, textShadowColor: colors.ink, textShadowRadius: 3 },
  giantDiscButton: { position: 'absolute', right: 8, zIndex: 2200, minWidth: 128, flexDirection: 'row', alignItems: 'center', gap: 7, borderWidth: 2, borderRadius: 17, paddingHorizontal: 10, paddingVertical: 7, shadowOpacity: 0.8, shadowRadius: 8, elevation: 9 },
  giantDiscButtonDisabled: { opacity: 0.42 },
  giantDiscButtonPressed: { transform: [{ scale: 0.94 }] },
  giantDiscButtonTitle: { fontFamily: fonts.extraBold, fontSize: 12, color: colors.white },
  giantDiscButtonCount: { fontFamily: fonts.bold, fontSize: 8 },
  notice: { position: 'absolute', alignSelf: 'center', top: '42%', fontFamily: fonts.display, fontSize: 31, color: colors.purple, textShadowColor: colors.white, textShadowRadius: 7, zIndex: 2100 },
  startOverlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(255,248,231,0.88)', alignItems: 'center', justifyContent: 'center', zIndex: 3000, padding: 20 },
  readyTitle: { fontFamily: fonts.display, fontSize: 31, color: colors.ink, marginTop: 5 },
  readyText: { fontFamily: fonts.medium, fontSize: 11, color: colors.muted, marginBottom: 12 },
  autoReadyText: { fontFamily: fonts.bold, fontSize: 10, color: colors.blueDark, marginTop: -7, marginBottom: 11, textAlign: 'center' },
  battleProgressText: { fontFamily: fonts.extraBold, fontSize: 10, color: colors.purple, marginBottom: 9 },
  startButton: { width: 210 },
  weaponHint: { fontFamily: fonts.bold, fontSize: 10, color: colors.red, marginTop: 8 },
  resultOverlay: { flex: 1, backgroundColor: colors.overlay, alignItems: 'center', justifyContent: 'center', padding: 24 },
  resultCard: { width: '100%', maxWidth: 380, backgroundColor: colors.cream, borderRadius: 28, padding: 22, alignItems: 'center', borderWidth: 3, borderColor: colors.white },
  resultEmoji: { fontSize: 58 },
  resultTitle: { fontFamily: fonts.display, fontSize: 34, color: colors.greenDark },
  defeatTitle: { color: colors.orange },
  rewardBox: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, backgroundColor: '#FFF0C2', borderRadius: 18, padding: 12, marginTop: 10 },
  replayBox: { backgroundColor: '#EEEAE6' },
  rewardLabel: { fontFamily: fonts.medium, fontSize: 10, color: colors.muted },
  rewardValue: { fontFamily: fonts.extraBold, fontSize: 17, color: colors.cookieDark },
  defeatText: { fontFamily: fonts.medium, fontSize: 12, lineHeight: 18, color: colors.muted, textAlign: 'center', marginVertical: 12 },
  progressText: { fontFamily: fonts.extraBold, fontSize: 13, color: colors.blueDark, marginTop: 10 },
  unlockText: { fontFamily: fonts.extraBold, fontSize: 13, color: colors.purple, marginTop: 10 },
  resultButtonRow: { width: '100%', flexDirection: 'row', gap: 10, marginTop: 14 },
  resultButton: { flex: 1 },
});
