import React from 'react';
import { Image, ImageSourcePropType } from 'react-native';

const bossAnimationImages: Record<string, ImageSourcePropType> = {
  'boss-easy-crumb-knight-walk-1': require('../../../assets/images/enemies/animations/boss-easy-crumb-knight-walk-1.webp'),
  'boss-easy-crumb-knight-walk-2': require('../../../assets/images/enemies/animations/boss-easy-crumb-knight-walk-2.webp'),
  'boss-easy-crumb-knight-walk-3': require('../../../assets/images/enemies/animations/boss-easy-crumb-knight-walk-3.webp'),
  'boss-easy-crumb-knight-hammer-windup': require('../../../assets/images/enemies/animations/boss-easy-crumb-knight-hammer-windup.webp'),
  'boss-easy-crumb-knight-hammer-impact': require('../../../assets/images/enemies/animations/boss-easy-crumb-knight-hammer-impact.webp'),
  'boss-easy-crumb-knight-hammer-recovery': require('../../../assets/images/enemies/animations/boss-easy-crumb-knight-hammer-recovery.webp'),
  'boss-normal-caramel-general-walk-1': require('../../../assets/images/enemies/animations/boss-normal-caramel-general-walk-1.webp'),
  'boss-normal-caramel-general-walk-2': require('../../../assets/images/enemies/animations/boss-normal-caramel-general-walk-2.webp'),
  'boss-normal-caramel-general-walk-3': require('../../../assets/images/enemies/animations/boss-normal-caramel-general-walk-3.webp'),
  'boss-normal-caramel-general-hammer-windup': require('../../../assets/images/enemies/animations/boss-normal-caramel-general-hammer-windup.webp'),
  'boss-normal-caramel-general-hammer-impact': require('../../../assets/images/enemies/animations/boss-normal-caramel-general-hammer-impact.webp'),
  'boss-normal-caramel-general-hammer-recovery': require('../../../assets/images/enemies/animations/boss-normal-caramel-general-hammer-recovery.webp'),
  'boss-hard-frost-viking-walk-1': require('../../../assets/images/enemies/animations/boss-hard-frost-viking-walk-1.webp'),
  'boss-hard-frost-viking-walk-2': require('../../../assets/images/enemies/animations/boss-hard-frost-viking-walk-2.webp'),
  'boss-hard-frost-viking-walk-3': require('../../../assets/images/enemies/animations/boss-hard-frost-viking-walk-3.webp'),
  'boss-hard-frost-viking-hammer-windup': require('../../../assets/images/enemies/animations/boss-hard-frost-viking-hammer-windup.webp'),
  'boss-hard-frost-viking-hammer-impact': require('../../../assets/images/enemies/animations/boss-hard-frost-viking-hammer-impact.webp'),
  'boss-hard-frost-viking-hammer-recovery': require('../../../assets/images/enemies/animations/boss-hard-frost-viking-hammer-recovery.webp'),
  'boss-harder-jungle-golem-walk-1': require('../../../assets/images/enemies/animations/boss-harder-jungle-golem-walk-1.webp'),
  'boss-harder-jungle-golem-walk-2': require('../../../assets/images/enemies/animations/boss-harder-jungle-golem-walk-2.webp'),
  'boss-harder-jungle-golem-walk-3': require('../../../assets/images/enemies/animations/boss-harder-jungle-golem-walk-3.webp'),
  'boss-harder-jungle-golem-hammer-windup': require('../../../assets/images/enemies/animations/boss-harder-jungle-golem-hammer-windup.webp'),
  'boss-harder-jungle-golem-hammer-impact': require('../../../assets/images/enemies/animations/boss-harder-jungle-golem-hammer-impact.webp'),
  'boss-harder-jungle-golem-hammer-recovery': require('../../../assets/images/enemies/animations/boss-harder-jungle-golem-hammer-recovery.webp'),
  'boss-insane-storm-warden-walk-1': require('../../../assets/images/enemies/animations/boss-insane-storm-warden-walk-1.webp'),
  'boss-insane-storm-warden-walk-2': require('../../../assets/images/enemies/animations/boss-insane-storm-warden-walk-2.webp'),
  'boss-insane-storm-warden-walk-3': require('../../../assets/images/enemies/animations/boss-insane-storm-warden-walk-3.webp'),
  'boss-insane-storm-warden-hammer-windup': require('../../../assets/images/enemies/animations/boss-insane-storm-warden-hammer-windup.webp'),
  'boss-insane-storm-warden-hammer-impact': require('../../../assets/images/enemies/animations/boss-insane-storm-warden-hammer-impact.webp'),
  'boss-insane-storm-warden-hammer-recovery': require('../../../assets/images/enemies/animations/boss-insane-storm-warden-hammer-recovery.webp'),
  'boss-easy-demon-ember-brute-walk-1': require('../../../assets/images/enemies/animations/boss-easy-demon-ember-brute-walk-1.webp'),
  'boss-easy-demon-ember-brute-walk-2': require('../../../assets/images/enemies/animations/boss-easy-demon-ember-brute-walk-2.webp'),
  'boss-easy-demon-ember-brute-walk-3': require('../../../assets/images/enemies/animations/boss-easy-demon-ember-brute-walk-3.webp'),
  'boss-easy-demon-ember-brute-hammer-windup': require('../../../assets/images/enemies/animations/boss-easy-demon-ember-brute-hammer-windup.webp'),
  'boss-easy-demon-ember-brute-hammer-impact': require('../../../assets/images/enemies/animations/boss-easy-demon-ember-brute-hammer-impact.webp'),
  'boss-easy-demon-ember-brute-hammer-recovery': require('../../../assets/images/enemies/animations/boss-easy-demon-ember-brute-hammer-recovery.webp'),
  'boss-medium-demon-marsh-witch-walk-1': require('../../../assets/images/enemies/animations/boss-medium-demon-marsh-witch-walk-1.webp'),
  'boss-medium-demon-marsh-witch-walk-2': require('../../../assets/images/enemies/animations/boss-medium-demon-marsh-witch-walk-2.webp'),
  'boss-medium-demon-marsh-witch-walk-3': require('../../../assets/images/enemies/animations/boss-medium-demon-marsh-witch-walk-3.webp'),
  'boss-medium-demon-marsh-witch-hammer-windup': require('../../../assets/images/enemies/animations/boss-medium-demon-marsh-witch-hammer-windup.webp'),
  'boss-medium-demon-marsh-witch-hammer-impact': require('../../../assets/images/enemies/animations/boss-medium-demon-marsh-witch-hammer-impact.webp'),
  'boss-medium-demon-marsh-witch-hammer-recovery': require('../../../assets/images/enemies/animations/boss-medium-demon-marsh-witch-hammer-recovery.webp'),
  'boss-hard-demon-bone-king-walk-1': require('../../../assets/images/enemies/animations/boss-hard-demon-bone-king-walk-1.webp'),
  'boss-hard-demon-bone-king-walk-2': require('../../../assets/images/enemies/animations/boss-hard-demon-bone-king-walk-2.webp'),
  'boss-hard-demon-bone-king-walk-3': require('../../../assets/images/enemies/animations/boss-hard-demon-bone-king-walk-3.webp'),
  'boss-hard-demon-bone-king-hammer-windup': require('../../../assets/images/enemies/animations/boss-hard-demon-bone-king-hammer-windup.webp'),
  'boss-hard-demon-bone-king-hammer-impact': require('../../../assets/images/enemies/animations/boss-hard-demon-bone-king-hammer-impact.webp'),
  'boss-hard-demon-bone-king-hammer-recovery': require('../../../assets/images/enemies/animations/boss-hard-demon-bone-king-hammer-recovery.webp'),
  'boss-insane-demon-blood-knight-walk-1': require('../../../assets/images/enemies/animations/boss-insane-demon-blood-knight-walk-1.webp'),
  'boss-insane-demon-blood-knight-walk-2': require('../../../assets/images/enemies/animations/boss-insane-demon-blood-knight-walk-2.webp'),
  'boss-insane-demon-blood-knight-walk-3': require('../../../assets/images/enemies/animations/boss-insane-demon-blood-knight-walk-3.webp'),
  'boss-insane-demon-blood-knight-hammer-windup': require('../../../assets/images/enemies/animations/boss-insane-demon-blood-knight-hammer-windup.webp'),
  'boss-insane-demon-blood-knight-hammer-impact': require('../../../assets/images/enemies/animations/boss-insane-demon-blood-knight-hammer-impact.webp'),
  'boss-insane-demon-blood-knight-hammer-recovery': require('../../../assets/images/enemies/animations/boss-insane-demon-blood-knight-hammer-recovery.webp'),
  'boss-extreme-demon-inferno-titan-walk-1': require('../../../assets/images/enemies/animations/boss-extreme-demon-inferno-titan-walk-1.webp'),
  'boss-extreme-demon-inferno-titan-walk-2': require('../../../assets/images/enemies/animations/boss-extreme-demon-inferno-titan-walk-2.webp'),
  'boss-extreme-demon-inferno-titan-walk-3': require('../../../assets/images/enemies/animations/boss-extreme-demon-inferno-titan-walk-3.webp'),
  'boss-extreme-demon-inferno-titan-hammer-windup': require('../../../assets/images/enemies/animations/boss-extreme-demon-inferno-titan-hammer-windup.webp'),
  'boss-extreme-demon-inferno-titan-hammer-impact': require('../../../assets/images/enemies/animations/boss-extreme-demon-inferno-titan-hammer-impact.webp'),
  'boss-extreme-demon-inferno-titan-hammer-recovery': require('../../../assets/images/enemies/animations/boss-extreme-demon-inferno-titan-hammer-recovery.webp'),
  'boss-easy-god-cloud-guardian-walk-1': require('../../../assets/images/enemies/animations/boss-easy-god-cloud-guardian-walk-1.webp'),
  'boss-easy-god-cloud-guardian-walk-2': require('../../../assets/images/enemies/animations/boss-easy-god-cloud-guardian-walk-2.webp'),
  'boss-easy-god-cloud-guardian-walk-3': require('../../../assets/images/enemies/animations/boss-easy-god-cloud-guardian-walk-3.webp'),
  'boss-easy-god-cloud-guardian-hammer-windup': require('../../../assets/images/enemies/animations/boss-easy-god-cloud-guardian-hammer-windup.webp'),
  'boss-easy-god-cloud-guardian-hammer-impact': require('../../../assets/images/enemies/animations/boss-easy-god-cloud-guardian-hammer-impact.webp'),
  'boss-easy-god-cloud-guardian-hammer-recovery': require('../../../assets/images/enemies/animations/boss-easy-god-cloud-guardian-hammer-recovery.webp'),
  'boss-medium-god-crystal-seraph-walk-1': require('../../../assets/images/enemies/animations/boss-medium-god-crystal-seraph-walk-1.webp'),
  'boss-medium-god-crystal-seraph-walk-2': require('../../../assets/images/enemies/animations/boss-medium-god-crystal-seraph-walk-2.webp'),
  'boss-medium-god-crystal-seraph-walk-3': require('../../../assets/images/enemies/animations/boss-medium-god-crystal-seraph-walk-3.webp'),
  'boss-medium-god-crystal-seraph-hammer-windup': require('../../../assets/images/enemies/animations/boss-medium-god-crystal-seraph-hammer-windup.webp'),
  'boss-medium-god-crystal-seraph-hammer-impact': require('../../../assets/images/enemies/animations/boss-medium-god-crystal-seraph-hammer-impact.webp'),
  'boss-medium-god-crystal-seraph-hammer-recovery': require('../../../assets/images/enemies/animations/boss-medium-god-crystal-seraph-hammer-recovery.webp'),
  'boss-hard-god-time-colossus-walk-1': require('../../../assets/images/enemies/animations/boss-hard-god-time-colossus-walk-1.webp'),
  'boss-hard-god-time-colossus-walk-2': require('../../../assets/images/enemies/animations/boss-hard-god-time-colossus-walk-2.webp'),
  'boss-hard-god-time-colossus-walk-3': require('../../../assets/images/enemies/animations/boss-hard-god-time-colossus-walk-3.webp'),
  'boss-hard-god-time-colossus-hammer-windup': require('../../../assets/images/enemies/animations/boss-hard-god-time-colossus-hammer-windup.webp'),
  'boss-hard-god-time-colossus-hammer-impact': require('../../../assets/images/enemies/animations/boss-hard-god-time-colossus-hammer-impact.webp'),
  'boss-hard-god-time-colossus-hammer-recovery': require('../../../assets/images/enemies/animations/boss-hard-god-time-colossus-hammer-recovery.webp'),
  'boss-insane-god-thunder-titan-walk-1': require('../../../assets/images/enemies/animations/boss-insane-god-thunder-titan-walk-1.webp'),
  'boss-insane-god-thunder-titan-walk-2': require('../../../assets/images/enemies/animations/boss-insane-god-thunder-titan-walk-2.webp'),
  'boss-insane-god-thunder-titan-walk-3': require('../../../assets/images/enemies/animations/boss-insane-god-thunder-titan-walk-3.webp'),
  'boss-insane-god-thunder-titan-hammer-windup': require('../../../assets/images/enemies/animations/boss-insane-god-thunder-titan-hammer-windup.webp'),
  'boss-insane-god-thunder-titan-hammer-impact': require('../../../assets/images/enemies/animations/boss-insane-god-thunder-titan-hammer-impact.webp'),
  'boss-insane-god-thunder-titan-hammer-recovery': require('../../../assets/images/enemies/animations/boss-insane-god-thunder-titan-hammer-recovery.webp'),
  'boss-extreme-god-void-emperor-walk-1': require('../../../assets/images/enemies/animations/boss-extreme-god-void-emperor-walk-1.webp'),
  'boss-extreme-god-void-emperor-walk-2': require('../../../assets/images/enemies/animations/boss-extreme-god-void-emperor-walk-2.webp'),
  'boss-extreme-god-void-emperor-walk-3': require('../../../assets/images/enemies/animations/boss-extreme-god-void-emperor-walk-3.webp'),
  'boss-extreme-god-void-emperor-hammer-windup': require('../../../assets/images/enemies/animations/boss-extreme-god-void-emperor-hammer-windup.webp'),
  'boss-extreme-god-void-emperor-hammer-impact': require('../../../assets/images/enemies/animations/boss-extreme-god-void-emperor-hammer-impact.webp'),
  'boss-extreme-god-void-emperor-hammer-recovery': require('../../../assets/images/enemies/animations/boss-extreme-god-void-emperor-hammer-recovery.webp'),
  'boss-easy-titan-crystal-giant-walk-1': require('../../../assets/images/enemies/animations/boss-easy-titan-crystal-giant-walk-1.webp'),
  'boss-easy-titan-crystal-giant-walk-2': require('../../../assets/images/enemies/animations/boss-easy-titan-crystal-giant-walk-2.webp'),
  'boss-easy-titan-crystal-giant-walk-3': require('../../../assets/images/enemies/animations/boss-easy-titan-crystal-giant-walk-3.webp'),
  'boss-easy-titan-crystal-giant-hammer-windup': require('../../../assets/images/enemies/animations/boss-easy-titan-crystal-giant-hammer-windup.webp'),
  'boss-easy-titan-crystal-giant-hammer-impact': require('../../../assets/images/enemies/animations/boss-easy-titan-crystal-giant-hammer-impact.webp'),
  'boss-easy-titan-crystal-giant-hammer-recovery': require('../../../assets/images/enemies/animations/boss-easy-titan-crystal-giant-hammer-recovery.webp'),
  'boss-medium-titan-spore-colossus-walk-1': require('../../../assets/images/enemies/animations/boss-medium-titan-spore-colossus-walk-1.webp'),
  'boss-medium-titan-spore-colossus-walk-2': require('../../../assets/images/enemies/animations/boss-medium-titan-spore-colossus-walk-2.webp'),
  'boss-medium-titan-spore-colossus-walk-3': require('../../../assets/images/enemies/animations/boss-medium-titan-spore-colossus-walk-3.webp'),
  'boss-medium-titan-spore-colossus-hammer-windup': require('../../../assets/images/enemies/animations/boss-medium-titan-spore-colossus-hammer-windup.webp'),
  'boss-medium-titan-spore-colossus-hammer-impact': require('../../../assets/images/enemies/animations/boss-medium-titan-spore-colossus-hammer-impact.webp'),
  'boss-medium-titan-spore-colossus-hammer-recovery': require('../../../assets/images/enemies/animations/boss-medium-titan-spore-colossus-hammer-recovery.webp'),
  'boss-hard-titan-steam-juggernaut-walk-1': require('../../../assets/images/enemies/animations/boss-hard-titan-steam-juggernaut-walk-1.webp'),
  'boss-hard-titan-steam-juggernaut-walk-2': require('../../../assets/images/enemies/animations/boss-hard-titan-steam-juggernaut-walk-2.webp'),
  'boss-hard-titan-steam-juggernaut-walk-3': require('../../../assets/images/enemies/animations/boss-hard-titan-steam-juggernaut-walk-3.webp'),
  'boss-hard-titan-steam-juggernaut-hammer-windup': require('../../../assets/images/enemies/animations/boss-hard-titan-steam-juggernaut-hammer-windup.webp'),
  'boss-hard-titan-steam-juggernaut-hammer-impact': require('../../../assets/images/enemies/animations/boss-hard-titan-steam-juggernaut-hammer-impact.webp'),
  'boss-hard-titan-steam-juggernaut-hammer-recovery': require('../../../assets/images/enemies/animations/boss-hard-titan-steam-juggernaut-hammer-recovery.webp'),
  'boss-insane-titan-coral-leviathan-walk-1': require('../../../assets/images/enemies/animations/boss-insane-titan-coral-leviathan-walk-1.webp'),
  'boss-insane-titan-coral-leviathan-walk-2': require('../../../assets/images/enemies/animations/boss-insane-titan-coral-leviathan-walk-2.webp'),
  'boss-insane-titan-coral-leviathan-walk-3': require('../../../assets/images/enemies/animations/boss-insane-titan-coral-leviathan-walk-3.webp'),
  'boss-insane-titan-coral-leviathan-hammer-windup': require('../../../assets/images/enemies/animations/boss-insane-titan-coral-leviathan-hammer-windup.webp'),
  'boss-insane-titan-coral-leviathan-hammer-impact': require('../../../assets/images/enemies/animations/boss-insane-titan-coral-leviathan-hammer-impact.webp'),
  'boss-insane-titan-coral-leviathan-hammer-recovery': require('../../../assets/images/enemies/animations/boss-insane-titan-coral-leviathan-hammer-recovery.webp'),
  'boss-extreme-titan-meteor-core-walk-1': require('../../../assets/images/enemies/animations/boss-extreme-titan-meteor-core-walk-1.webp'),
  'boss-extreme-titan-meteor-core-walk-2': require('../../../assets/images/enemies/animations/boss-extreme-titan-meteor-core-walk-2.webp'),
  'boss-extreme-titan-meteor-core-walk-3': require('../../../assets/images/enemies/animations/boss-extreme-titan-meteor-core-walk-3.webp'),
  'boss-extreme-titan-meteor-core-hammer-windup': require('../../../assets/images/enemies/animations/boss-extreme-titan-meteor-core-hammer-windup.webp'),
  'boss-extreme-titan-meteor-core-hammer-impact': require('../../../assets/images/enemies/animations/boss-extreme-titan-meteor-core-hammer-impact.webp'),
  'boss-extreme-titan-meteor-core-hammer-recovery': require('../../../assets/images/enemies/animations/boss-extreme-titan-meteor-core-hammer-recovery.webp'),
  'boss-easy-creator-clockwork-artisan-walk-1': require('../../../assets/images/enemies/animations/boss-easy-creator-clockwork-artisan-walk-1.webp'),
  'boss-easy-creator-clockwork-artisan-walk-2': require('../../../assets/images/enemies/animations/boss-easy-creator-clockwork-artisan-walk-2.webp'),
  'boss-easy-creator-clockwork-artisan-walk-3': require('../../../assets/images/enemies/animations/boss-easy-creator-clockwork-artisan-walk-3.webp'),
  'boss-easy-creator-clockwork-artisan-hammer-windup': require('../../../assets/images/enemies/animations/boss-easy-creator-clockwork-artisan-hammer-windup.webp'),
  'boss-easy-creator-clockwork-artisan-hammer-impact': require('../../../assets/images/enemies/animations/boss-easy-creator-clockwork-artisan-hammer-impact.webp'),
  'boss-easy-creator-clockwork-artisan-hammer-recovery': require('../../../assets/images/enemies/animations/boss-easy-creator-clockwork-artisan-hammer-recovery.webp'),
  'boss-medium-creator-rune-archivist-walk-1': require('../../../assets/images/enemies/animations/boss-medium-creator-rune-archivist-walk-1.webp'),
  'boss-medium-creator-rune-archivist-walk-2': require('../../../assets/images/enemies/animations/boss-medium-creator-rune-archivist-walk-2.webp'),
  'boss-medium-creator-rune-archivist-walk-3': require('../../../assets/images/enemies/animations/boss-medium-creator-rune-archivist-walk-3.webp'),
  'boss-medium-creator-rune-archivist-hammer-windup': require('../../../assets/images/enemies/animations/boss-medium-creator-rune-archivist-hammer-windup.webp'),
  'boss-medium-creator-rune-archivist-hammer-impact': require('../../../assets/images/enemies/animations/boss-medium-creator-rune-archivist-hammer-impact.webp'),
  'boss-medium-creator-rune-archivist-hammer-recovery': require('../../../assets/images/enemies/animations/boss-medium-creator-rune-archivist-hammer-recovery.webp'),
  'boss-hard-creator-mask-sculptor-walk-1': require('../../../assets/images/enemies/animations/boss-hard-creator-mask-sculptor-walk-1.webp'),
  'boss-hard-creator-mask-sculptor-walk-2': require('../../../assets/images/enemies/animations/boss-hard-creator-mask-sculptor-walk-2.webp'),
  'boss-hard-creator-mask-sculptor-walk-3': require('../../../assets/images/enemies/animations/boss-hard-creator-mask-sculptor-walk-3.webp'),
  'boss-hard-creator-mask-sculptor-hammer-windup': require('../../../assets/images/enemies/animations/boss-hard-creator-mask-sculptor-hammer-windup.webp'),
  'boss-hard-creator-mask-sculptor-hammer-impact': require('../../../assets/images/enemies/animations/boss-hard-creator-mask-sculptor-hammer-impact.webp'),
  'boss-hard-creator-mask-sculptor-hammer-recovery': require('../../../assets/images/enemies/animations/boss-hard-creator-mask-sculptor-hammer-recovery.webp'),
  'boss-insane-creator-life-alchemist-walk-1': require('../../../assets/images/enemies/animations/boss-insane-creator-life-alchemist-walk-1.webp'),
  'boss-insane-creator-life-alchemist-walk-2': require('../../../assets/images/enemies/animations/boss-insane-creator-life-alchemist-walk-2.webp'),
  'boss-insane-creator-life-alchemist-walk-3': require('../../../assets/images/enemies/animations/boss-insane-creator-life-alchemist-walk-3.webp'),
  'boss-insane-creator-life-alchemist-hammer-windup': require('../../../assets/images/enemies/animations/boss-insane-creator-life-alchemist-hammer-windup.webp'),
  'boss-insane-creator-life-alchemist-hammer-impact': require('../../../assets/images/enemies/animations/boss-insane-creator-life-alchemist-hammer-impact.webp'),
  'boss-insane-creator-life-alchemist-hammer-recovery': require('../../../assets/images/enemies/animations/boss-insane-creator-life-alchemist-hammer-recovery.webp'),
  'boss-extreme-creator-nebula-architect-walk-1': require('../../../assets/images/enemies/animations/boss-extreme-creator-nebula-architect-walk-1.webp'),
  'boss-extreme-creator-nebula-architect-walk-2': require('../../../assets/images/enemies/animations/boss-extreme-creator-nebula-architect-walk-2.webp'),
  'boss-extreme-creator-nebula-architect-walk-3': require('../../../assets/images/enemies/animations/boss-extreme-creator-nebula-architect-walk-3.webp'),
  'boss-extreme-creator-nebula-architect-hammer-windup': require('../../../assets/images/enemies/animations/boss-extreme-creator-nebula-architect-hammer-windup.webp'),
  'boss-extreme-creator-nebula-architect-hammer-impact': require('../../../assets/images/enemies/animations/boss-extreme-creator-nebula-architect-hammer-impact.webp'),
  'boss-extreme-creator-nebula-architect-hammer-recovery': require('../../../assets/images/enemies/animations/boss-extreme-creator-nebula-architect-hammer-recovery.webp'),
  'boss-easy-infinity-mirror-knight-walk-1': require('../../../assets/images/enemies/animations/boss-easy-infinity-mirror-knight-walk-1.webp'),
  'boss-easy-infinity-mirror-knight-walk-2': require('../../../assets/images/enemies/animations/boss-easy-infinity-mirror-knight-walk-2.webp'),
  'boss-easy-infinity-mirror-knight-walk-3': require('../../../assets/images/enemies/animations/boss-easy-infinity-mirror-knight-walk-3.webp'),
  'boss-easy-infinity-mirror-knight-hammer-windup': require('../../../assets/images/enemies/animations/boss-easy-infinity-mirror-knight-hammer-windup.webp'),
  'boss-easy-infinity-mirror-knight-hammer-impact': require('../../../assets/images/enemies/animations/boss-easy-infinity-mirror-knight-hammer-impact.webp'),
  'boss-easy-infinity-mirror-knight-hammer-recovery': require('../../../assets/images/enemies/animations/boss-easy-infinity-mirror-knight-hammer-recovery.webp'),
  'boss-medium-infinity-fractal-colossus-walk-1': require('../../../assets/images/enemies/animations/boss-medium-infinity-fractal-colossus-walk-1.webp'),
  'boss-medium-infinity-fractal-colossus-walk-2': require('../../../assets/images/enemies/animations/boss-medium-infinity-fractal-colossus-walk-2.webp'),
  'boss-medium-infinity-fractal-colossus-walk-3': require('../../../assets/images/enemies/animations/boss-medium-infinity-fractal-colossus-walk-3.webp'),
  'boss-medium-infinity-fractal-colossus-hammer-windup': require('../../../assets/images/enemies/animations/boss-medium-infinity-fractal-colossus-hammer-windup.webp'),
  'boss-medium-infinity-fractal-colossus-hammer-impact': require('../../../assets/images/enemies/animations/boss-medium-infinity-fractal-colossus-hammer-impact.webp'),
  'boss-medium-infinity-fractal-colossus-hammer-recovery': require('../../../assets/images/enemies/animations/boss-medium-infinity-fractal-colossus-hammer-recovery.webp'),
  'boss-hard-infinity-gravity-sovereign-walk-1': require('../../../assets/images/enemies/animations/boss-hard-infinity-gravity-sovereign-walk-1.webp'),
  'boss-hard-infinity-gravity-sovereign-walk-2': require('../../../assets/images/enemies/animations/boss-hard-infinity-gravity-sovereign-walk-2.webp'),
  'boss-hard-infinity-gravity-sovereign-walk-3': require('../../../assets/images/enemies/animations/boss-hard-infinity-gravity-sovereign-walk-3.webp'),
  'boss-hard-infinity-gravity-sovereign-hammer-windup': require('../../../assets/images/enemies/animations/boss-hard-infinity-gravity-sovereign-hammer-windup.webp'),
  'boss-hard-infinity-gravity-sovereign-hammer-impact': require('../../../assets/images/enemies/animations/boss-hard-infinity-gravity-sovereign-hammer-impact.webp'),
  'boss-hard-infinity-gravity-sovereign-hammer-recovery': require('../../../assets/images/enemies/animations/boss-hard-infinity-gravity-sovereign-hammer-recovery.webp'),
  'boss-insane-infinity-eternity-emperor-walk-1': require('../../../assets/images/enemies/animations/boss-insane-infinity-eternity-emperor-walk-1.webp'),
  'boss-insane-infinity-eternity-emperor-walk-2': require('../../../assets/images/enemies/animations/boss-insane-infinity-eternity-emperor-walk-2.webp'),
  'boss-insane-infinity-eternity-emperor-walk-3': require('../../../assets/images/enemies/animations/boss-insane-infinity-eternity-emperor-walk-3.webp'),
  'boss-insane-infinity-eternity-emperor-hammer-windup': require('../../../assets/images/enemies/animations/boss-insane-infinity-eternity-emperor-hammer-windup.webp'),
  'boss-insane-infinity-eternity-emperor-hammer-impact': require('../../../assets/images/enemies/animations/boss-insane-infinity-eternity-emperor-hammer-impact.webp'),
  'boss-insane-infinity-eternity-emperor-hammer-recovery': require('../../../assets/images/enemies/animations/boss-insane-infinity-eternity-emperor-hammer-recovery.webp'),
  'boss-extreme-infinity-multiverse-lord-walk-1': require('../../../assets/images/enemies/animations/boss-extreme-infinity-multiverse-lord-walk-1.webp'),
  'boss-extreme-infinity-multiverse-lord-walk-2': require('../../../assets/images/enemies/animations/boss-extreme-infinity-multiverse-lord-walk-2.webp'),
  'boss-extreme-infinity-multiverse-lord-walk-3': require('../../../assets/images/enemies/animations/boss-extreme-infinity-multiverse-lord-walk-3.webp'),
  'boss-extreme-infinity-multiverse-lord-hammer-windup': require('../../../assets/images/enemies/animations/boss-extreme-infinity-multiverse-lord-hammer-windup.webp'),
  'boss-extreme-infinity-multiverse-lord-hammer-impact': require('../../../assets/images/enemies/animations/boss-extreme-infinity-multiverse-lord-hammer-impact.webp'),
  'boss-extreme-infinity-multiverse-lord-hammer-recovery': require('../../../assets/images/enemies/animations/boss-extreme-infinity-multiverse-lord-hammer-recovery.webp'),
};

export function hasBossAnimationImage(imageKey: string): boolean {
  return bossAnimationImages[imageKey] !== undefined;
}

export const BossAnimationSprite = React.memo(function BossAnimationSprite({
  imageKey,
  size,
}: {
  imageKey: string;
  size: number;
}) {
  const source = bossAnimationImages[imageKey];
  if (!source) return null;
  return (
    <Image
      source={source}
      resizeMode="contain"
      style={{ width: size, height: size }}
    />
  );
});
