export type CookieFeedbackTier =
  | 'normal'
  | 'criticalFull'
  | 'criticalCompact'
  | 'superCriticalFull'
  | 'superCriticalCompact';

export interface CookieAudioFeedbackConfig {
  minimumClickIntervalMs: number;
  minimumFullCriticalIntervalMs: number;
  minimumFullSuperCriticalIntervalMs: number;
  criticalLayerDurationMs: number;
  criticalSparkleDelayMs: number;
  voicePlaybackRates: number[];
  voiceVolumeMultipliers: number[];
  criticalImpactVolumeMultiplier: number;
  criticalSparkleVolumeMultiplier: number;
  superCriticalImpactVolumeMultiplier: number;
  superCriticalShockwaveVolumeMultiplier: number;
  superCriticalShockwaveDelayMs: number;
  superCriticalLayerDurationMs: number;
}

export interface FloatingGainFeedbackConfig {
  durationMs: number;
  maximumConcurrent: number;
  normalFontSize: number;
  criticalFontSize: number;
  superCriticalFontSize: number;
  normalColor: string;
  criticalColor: string;
  superCriticalColor: string;
  normalShadowColor: string;
  criticalShadowColor: string;
  superCriticalShadowColor: string;
  normalShadowRadius: number;
  criticalShadowRadius: number;
  superCriticalShadowRadius: number;
  holdUntilProgress: number;
  risePixels: number;
  startScale: number;
  peakAtProgress: number;
  peakScale: number;
  endScale: number;
}

export interface CookieSuperCriticalEffectConfig {
  durationMs: number;
  compactDurationMs: number;
  sizePixels: number;
  maximumConcurrentFullEffects: number;
  maximumConcurrentCompactEffects: number;
  flashMaximumOpacity: number;
  compactFlashMaximumOpacity: number;
  flashStartScale: number;
  flashEndScale: number;
  flashRotationDegrees: number;
  impactPeakProgress: number;
  impactFadeStartProgress: number;
  chargeEndProgress: number;
  secondaryImpactProgress: number;
  shakeFirstProgress: number;
  shakeSecondProgress: number;
  shakeThirdProgress: number;
  shakeEndProgress: number;
  shakeDistancePixels: number;
  shakeReturnRatio: number;
  columnWidthPixels: number;
  columnLengthPixels: number;
  columnStartScale: number;
  columnPeakScale: number;
  columnEndScale: number;
  columnGradientColors: string[];
  slashCount: number;
  compactSlashCount: number;
  slashLengthPixels: number;
  slashWidthPixels: number;
  slashAngleOffsetDegrees: number;
  slashAngleStepDegrees: number;
  slashStartScale: number;
  slashPeakScale: number;
  slashEndScale: number;
  slashFadeStartProgress: number;
  slashRevealProgress: number;
  slashStaggerProgress: number;
  slashGradientColors: string[];
  ghostSlashColors: string[];
  ghostSlashOffsetPixels: number;
  lightningBranchCount: number;
  compactLightningBranchCount: number;
  lightningSegmentCount: number;
  lightningSegmentLengthPixels: number;
  lightningSegmentWidthPixels: number;
  lightningStartDistancePixels: number;
  lightningAngleOffsetDegrees: number;
  lightningSegmentTurnDegrees: number;
  lightningZigzagOffsetPixels: number;
  lightningRevealProgress: number;
  lightningBranchStaggerProgress: number;
  lightningSegmentStaggerProgress: number;
  lightningFadeStartProgress: number;
  lightningSegmentStartScale: number;
  lightningColors: string[];
  shardCount: number;
  compactShardCount: number;
  shardStartProgress: number;
  shardRevealProgress: number;
  shardFadeStartProgress: number;
  shardStartDistancePixels: number;
  shardEndDistancePixels: number;
  shardMinimumSizePixels: number;
  shardMaximumSizePixels: number;
  shardRotationTurns: number;
  shardAngleOffsetDegrees: number;
  shardColors: string[];
  riftSegmentCount: number;
  riftSegmentLengthPixels: number;
  riftSegmentWidthPixels: number;
  riftTopRatio: number;
  riftHorizontalSpreadRatio: number;
  riftZigzagPixels: number;
  riftTurnDegrees: number;
  riftRevealProgress: number;
  riftSegmentStaggerProgress: number;
  riftFadeStartProgress: number;
  riftStartScale: number;
  riftEndScale: number;
  riftGlowWidthMultiplier: number;
  riftGlowMaximumOpacity: number;
  riftColors: string[];
  compactScale: number;
  labelFontSize: number;
  labelTopRatio: number;
  labelShadowRadius: number;
  labelStartScale: number;
  labelPeakScale: number;
  labelEndScale: number;
  emblemSizePixels: number;
  emblemTopRatio: number;
  emblemStartScale: number;
  emblemPeakScale: number;
  emblemEndScale: number;
  emblemFadeStartProgress: number;
  emblemRotationDegrees: number;
  shockwaveCount: number;
  shockwaveSizePixels: number;
  shockwaveBorderWidthPixels: number;
  shockwaveStaggerProgress: number;
  shockwaveEndScale: number;
  shockwaveCornerRadiusRatio: number;
  shockwaveRotationDegrees: number;
  shockwaveColor: string;
  flashColor: string;
  labelColor: string;
  labelShadowColor: string;
}

export interface CookieFeedbackConfig {
  audio: CookieAudioFeedbackConfig;
  floatingGain: FloatingGainFeedbackConfig;
  superCriticalEffect: CookieSuperCriticalEffectConfig;
}
