import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { fonts } from '../../theme/typography';

export const gameScreenStyles = StyleSheet.create({
  root: { flex: 1, paddingVertical: 4 },
  statsRow: { flexDirection: 'row', gap: 6 },
  hero: {
    flex: 1,
    minHeight: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
    paddingBottom: 6,
  },
  evolutionRemaining: {
    fontFamily: fonts.extraBold,
    fontSize: 13,
    color: colors.purple,
    textAlign: 'center',
  },
  evolutionSummary: { width: '92%', maxWidth: 360, alignItems: 'center' },
  evolutionProgressTrack: {
    width: '100%',
    height: 10,
    marginTop: 4,
    overflow: 'hidden',
    borderRadius: 5,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#D9BEFF',
  },
  evolutionProgressFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: colors.purple,
  },
  cookieStage: { width: 358, height: 358, alignItems: 'center', justifyContent: 'center' },
  ringOuter: {
    position: 'absolute',
    width: 350,
    height: 350,
    borderRadius: 175,
    backgroundColor: 'rgba(255, 200, 61, 0.22)',
    borderWidth: 3,
    borderColor: 'rgba(255, 169, 61, 0.32)',
  },
  ringInner: {
    position: 'absolute',
    width: 314,
    height: 314,
    borderRadius: 157,
    backgroundColor: 'rgba(255,255,255,0.55)',
  },
  cookieButton: {
    width: 310,
    height: 310,
    borderRadius: 155,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 6,
    borderColor: '#FFD97A',
    shadowColor: colors.shadow,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  infoGroup: { alignItems: 'center', maxWidth: '98%', gap: 2 },
  infoText: { fontFamily: fonts.extraBold, fontSize: 12, textAlign: 'center' },
  medalInfo: { color: colors.purple },
  autoInfo: { color: colors.muted },
  clickInfo: { color: colors.blue },
  clickerInfo: { color: colors.orange },
  flyingInfo: { color: colors.greenDark },
});
